### PR TITLE
Install content shell also

### PR DESCRIPTION
**Pull request by jefftougas**
I needed this for running unit tests locally that use the content shell. Thanks for this tool!

### CODE REVIEW

**Comment by cbracken** [comment]
Turns out I wasn't watching my own repo! Corrected that now. I'll take a look at this tonight and merge. Thanks for the PR!

**Comment by jefftougas** [comment]
@cbracken no worries. I've gone ahead and rebased from your latest, and removed the version bump from my commit since it seems like you handle that yourself outside of PRs after they're merged. Let me know if you'd prefer that I include the version bump in here.

**Comment by cbracken** [comment]
Merged! Thanks for rebasing. This PR also led me to spot a bug in the Dartium launch script. Fixed in e200c4d542f99f3843e64ab5af3912dd6401fba3. Released as version 1.1.3.

Apologies again for not spotting this until now!

**Comment by jefftougas** [comment]
No worries! Thanks for this great tool!

**Pull request merged**
